use crate::error::DoctorResult;
use crate::model::report::DiagnosticReport;
use crate::model::Severity;
use std::io::Write;

/// Write diagnostic report as structured Markdown.
pub fn write(report: &DiagnosticReport, writer: &mut dyn Write) -> DoctorResult<()> {
    writeln!(writer, "# Doctor Diagnosis Report")?;
    writeln!(writer)?;
    writeln!(
        writer,
        "**Project**: `{}` | **Health Score**: `{}/100` | **Duration**: `{:.1}s`",
        report.project_name,
        report.health_score,
        report.duration_ms as f64 / 1000.0
    )?;
    writeln!(writer)?;

    // System Overview
    writeln!(writer, "## System Overview")?;
    writeln!(writer)?;
    writeln!(writer, "| Property | Value |")?;
    writeln!(writer, "|----------|-------|")?;
    writeln!(writer, "| Build Tool | {} |", report.system_overview.build_tool)?;
    writeln!(
        writer,
        "| Spring Boot | {} |",
        report.system_overview.spring_boot_version.as_deref().unwrap_or("N/A")
    )?;
    writeln!(
        writer,
        "| Java | {} |",
        report.system_overview.java_version.as_deref().unwrap_or("N/A")
    )?;
    if !report.system_overview.starters.is_empty() {
        writeln!(writer, "| Starters | {} |", report.system_overview.starters.join(", "))?;
    }
    writeln!(writer)?;

    // Health Score
    writeln!(writer, "## Health Score: `{}/100`", report.health_score)?;
    writeln!(writer)?;
    let bar_char = if report.health_score >= 80 {
        '█'
    } else if report.health_score >= 50 {
        '▓'
    } else {
        '░'
    };
    let filled = (report.health_score as usize) / 2;
    let empty = 50 - filled;
    writeln!(
        writer,
        "`{}{}`",
        bar_char.to_string().repeat(filled),
        "░".repeat(empty)
    )?;
    writeln!(writer)?;

    // Issues
    let error_count = report.issues.iter().filter(|i| i.severity == Severity::Error).count();
    let warn_count = report.issues.iter().filter(|i| i.severity == Severity::Warning).count();
    let info_count = report.issues.iter().filter(|i| i.severity == Severity::Info).count();
    writeln!(
        writer,
        "## Issues: {} ERROR | {} WARNING | {} INFO",
        error_count, warn_count, info_count
    )?;
    writeln!(writer)?;

    if report.issues.is_empty() {
        writeln!(writer, "✅ **No issues found!**")?;
    } else {
        for issue in &report.issues {
            let emoji = match issue.severity {
                Severity::Error => "🔴",
                Severity::Warning => "🟡",
                Severity::Info => "🔵",
            };
            writeln!(
                writer,
                "### {} [{}] [{}] {}",
                emoji, issue.severity, issue.category, issue.title
            )?;
            writeln!(writer)?;
            writeln!(writer, "{}", issue.description)?;
            writeln!(writer)?;

            if !issue.evidence.is_empty() {
                writeln!(writer, "**Evidence:**")?;
                writeln!(writer)?;
                for ev in issue.evidence.iter().take(5) {
                    writeln!(
                        writer,
                        "- `{}` — {} *(reliability: {})*",
                        ev.source, ev.summary, ev.reliability
                    )?;
                }
                if issue.evidence.len() > 5 {
                    writeln!(
                        writer,
                        "- ... and {} more evidence items",
                        issue.evidence.len() - 5
                    )?;
                }
                writeln!(writer)?;
            }

            if !issue.fix_suggestion.is_empty() {
                writeln!(writer, "**💡 Fix:** {}", issue.fix_suggestion)?;
                writeln!(writer)?;
            }

            writeln!(writer, "---")?;
            writeln!(writer)?;
        }
    }

    // Footer
    writeln!(writer, "---")?;
    writeln!(
        writer,
        "*Report generated by Doctor. Rules executed: {} | Evidence collected: {}*",
        report.summary.total_rules_executed, report.summary.total_evidence_collected
    )?;

    Ok(())
}
